select * from customer limit 20

-- what is total revenue generated by male vs female customers?
select gender,SUM(purchase_amount)as revenue
from customer
group by gender;

-- which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes'
and purchase_amount >= (select avg(purchase_amount) from customer);

-- which are the top 5 products with highest average review rating for sql query
select item_purchased,round(avg(review_rating)::numeric,2) as avg_review
from customer
group by item_purchased
order by avg_review desc
limit 5;

-- compare the average purchase amount between standard and express shipping
select shipping_type,ROUND(avg(purchase_amount)::NUMERIC,2)
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

-- DO SUBSCRIBED CUSTOMERS SPEND MORE?COMPARE AVERAGE SPEND AND 
-- TOTAL REVENUE BETWEEN SUBSCRIBER AND NON-SUBSCRIBER
SELECT SUBSCRIPTION_STATUS ,
COUNT(CUSTOMER_ID)AS TOTAL_CUSTOMERS,
ROUND(AVG(PURCHASE_AMOUNT)::NUMERIC,2) AS AVG_SPEND,
ROUND(SUM(PURCHASE_AMOUNT)::NUMERIC,2) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS
ORDER BY TOTAL_REVENUE ,AVG_SPEND DESC;

-- WHICH 5 PRODUCTS HAVE HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNT APPLIED?
SELECT ITEM_PURCHASED,
ROUND(100 * SUM(CASE WHEN DISCOUNT_APPLIED='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS DISCOUNT_PERCENTAGE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_PERCENTAGE DESC
LIMIT 5;

-- SEGMENT CUSTOMERS INTO NEW,RETURNING,AND LOYAL BASED ON THEIR TOTAL 
-- NUMBER OF PREVIOUS PURCHASES,AND SHOW THE COUNT OF EACH SEGMENT.
SELECT 
CASE 
    WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
    WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS CUSTOMER_SEGMENT,
COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMER
GROUP BY CUSTOMER_SEGMENT;

-- what are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased,
count(customer_id)as total_orders,
row_number() over(partition by category order by count(customer_id) desc)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- are customer who are repeat buyers(more than 5 previous purchases)also likely to subscribe?
select subscription_status,
count(customer_id)as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

-- what are the revenue contribution of each group?
select age_group,
sum(purchase_amount)as total_revenue
from customer 
group by age_group 
order by total_revenue desc;







